from os import name
import re
from pynput import keyboard


def press_hotkey(key_text: str):        
    key = text_to_key_dict[key_text]
    keyboard_controller.press(key)
    keyboard_controller.release(key)

keyboard_controller = keyboard.Controller()
text_to_key_dict = {
    "space": keyboard.Key.space,
    "!": "!",
    "\"": "\"",
    "#": "#",
    "$": "$", 
    "%": "%",
    "&": "&",
    "'": "'",
    "(": "(",
    ")": ")",
    "*": "*",
    "+": "+",
    ",": ",",
    "-": "-",
    ".": ".",
    "/": "/",
    "0": "0",
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6": "6",
    "7": "7",
    "8": "8",
    "9": "9",
    ":": ":",
    ";": ";",
    "<": "<",
    "=": "=",
    ">": ">",
    "?": "?",
    "@": "@",
    "a": "a",
    "b": "b",
    "c": "c",
    "d": "d",
    "e": "e",
    "f": "f",
    "g": "g",
    "h": "h",
    "i": "i",
    "j": "j",
    "k": "k",
    "l": "l",
    "m": "m",
    "n": "n",
    "o": "o",
    "p": "p",
    "q": "q",
    "r": "r",
    "s": "s",
    "t": "t",
    "u": "u",
    "v": "v",
    "w": "w",
    "x": "x",
    "y": "y",
    "Z": "z",
    "z": "z",
    "[": "[",
    "\\": "\\",
    "]": "]",
    "^": "^",
    "_": "_",
    "`": "`",
    "{": "{",
    "|": "|",
    "}": "}",
    "~": "~",
    "delete": keyboard.Key.delete,
    "return": keyboard.Key.enter,
    "esc": keyboard.Key.esc,
    "tab": keyboard.Key.tab,
    "backspace": keyboard.Key.backspace,
    "return": keyboard.Key.enter,
    "enter": keyboard.Key.enter,
    "delete": keyboard.Key.delete,
    "home": keyboard.Key.home,
    "end": keyboard.Key.end,
    "left": keyboard.Key.left,
    "up": keyboard.Key.up,
    "right": keyboard.Key.right,
    "down": keyboard.Key.down,
    "page up": keyboard.Key.page_up,
    "page down": keyboard.Key.page_down,
    "shift": keyboard.Key.shift,
    "ctrl": keyboard.Key.ctrl,
    "caps lock": keyboard.Key.caps_lock,
    "option": keyboard.Key.alt,
    "alt": keyboard.Key.alt,
    "cmd": keyboard.Key.cmd,
    "f1": keyboard.Key.f1,
    "f2": keyboard.Key.f2,
    "f3": keyboard.Key.f3,
    "f4": keyboard.Key.f4,
    "f5": keyboard.Key.f5,
    "f6": keyboard.Key.f6,
    "f7": keyboard.Key.f7,
    "f8": keyboard.Key.f8,
    "f9": keyboard.Key.f9,
    "f10": keyboard.Key.f10,
    "f11": keyboard.Key.f11,
    "f12": keyboard.Key.f12,
    "f13": keyboard.Key.f13,
    "f14": keyboard.Key.f14,
    "f15": keyboard.Key.f15,
    "f16": keyboard.Key.f16,
    "f17": keyboard.Key.f17,
    "f18": keyboard.Key.f18,
    "f19": keyboard.Key.f19,
    "f20": keyboard.Key.f20,
}


# name = "001_screenshot_[20]"
# pause = re.search(r"_\[(.+?)\]", name)
# print(pause[1])