# Read these from settings eventually (at least the flag stuff)
FRAME_WIDTH = 480
FRAME_HEIGHT = 360
DEFAULT_THRESHOLD = 0.90
DEFAULT_DELAY = 0
DEFAULT_LOOP_COUNT = 1
DEFAULT_PAUSE = 1
DEFAULT_FPS = 120
LAST_IMAGE_DIR = "res"
OPEN_SCREENSHOT_ON_CAPTURE = True
